/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace Wordbook
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class TDateTime : TBase
  {
    private short _year;
    private short _month;
    private short _day;
    private short _hour;
    private short _minute;
    private short _second;
    private short _millisecond;

    public short Year
    {
      get
      {
        return _year;
      }
      set
      {
        __isset.year = true;
        this._year = value;
      }
    }

    public short Month
    {
      get
      {
        return _month;
      }
      set
      {
        __isset.month = true;
        this._month = value;
      }
    }

    public short Day
    {
      get
      {
        return _day;
      }
      set
      {
        __isset.day = true;
        this._day = value;
      }
    }

    public short Hour
    {
      get
      {
        return _hour;
      }
      set
      {
        __isset.hour = true;
        this._hour = value;
      }
    }

    public short Minute
    {
      get
      {
        return _minute;
      }
      set
      {
        __isset.minute = true;
        this._minute = value;
      }
    }

    public short Second
    {
      get
      {
        return _second;
      }
      set
      {
        __isset.second = true;
        this._second = value;
      }
    }

    public short Millisecond
    {
      get
      {
        return _millisecond;
      }
      set
      {
        __isset.millisecond = true;
        this._millisecond = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool year;
      public bool month;
      public bool day;
      public bool hour;
      public bool minute;
      public bool second;
      public bool millisecond;
    }

    public TDateTime() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.I16) {
              Year = iprot.ReadI16();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.I16) {
              Month = iprot.ReadI16();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 3:
            if (field.Type == TType.I16) {
              Day = iprot.ReadI16();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 4:
            if (field.Type == TType.I16) {
              Hour = iprot.ReadI16();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 5:
            if (field.Type == TType.I16) {
              Minute = iprot.ReadI16();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 6:
            if (field.Type == TType.I16) {
              Second = iprot.ReadI16();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 7:
            if (field.Type == TType.I16) {
              Millisecond = iprot.ReadI16();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("TDateTime");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (__isset.year) {
        field.Name = "year";
        field.Type = TType.I16;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteI16(Year);
        oprot.WriteFieldEnd();
      }
      if (__isset.month) {
        field.Name = "month";
        field.Type = TType.I16;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        oprot.WriteI16(Month);
        oprot.WriteFieldEnd();
      }
      if (__isset.day) {
        field.Name = "day";
        field.Type = TType.I16;
        field.ID = 3;
        oprot.WriteFieldBegin(field);
        oprot.WriteI16(Day);
        oprot.WriteFieldEnd();
      }
      if (__isset.hour) {
        field.Name = "hour";
        field.Type = TType.I16;
        field.ID = 4;
        oprot.WriteFieldBegin(field);
        oprot.WriteI16(Hour);
        oprot.WriteFieldEnd();
      }
      if (__isset.minute) {
        field.Name = "minute";
        field.Type = TType.I16;
        field.ID = 5;
        oprot.WriteFieldBegin(field);
        oprot.WriteI16(Minute);
        oprot.WriteFieldEnd();
      }
      if (__isset.second) {
        field.Name = "second";
        field.Type = TType.I16;
        field.ID = 6;
        oprot.WriteFieldBegin(field);
        oprot.WriteI16(Second);
        oprot.WriteFieldEnd();
      }
      if (__isset.millisecond) {
        field.Name = "millisecond";
        field.Type = TType.I16;
        field.ID = 7;
        oprot.WriteFieldBegin(field);
        oprot.WriteI16(Millisecond);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("TDateTime(");
      sb.Append("Year: ");
      sb.Append(Year);
      sb.Append(",Month: ");
      sb.Append(Month);
      sb.Append(",Day: ");
      sb.Append(Day);
      sb.Append(",Hour: ");
      sb.Append(Hour);
      sb.Append(",Minute: ");
      sb.Append(Minute);
      sb.Append(",Second: ");
      sb.Append(Second);
      sb.Append(",Millisecond: ");
      sb.Append(Millisecond);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
